Improve error message when showing prompt in non-interactive shell (#235)
# Objective

Closes #212.

We are showing interactive prompts before we install any required
tooling.

In non-interactive shells (e.g. CI), this will fail with an error.

We should improve this error message to guide the user towards the
`--yes` flag, which confirms the prompts automatically.

# Solution

Use `anyhow`'s `.context(...)` to make the error message more useful,
guiding the user towards `--yes`.

# Testing

Tested in one of [testing repositories in
CI](https://github.com/TimJentzsch/bevy_complex_repo/actions/runs/12867761889/job/35873080585?pr=1#step:6:9).

New output:

```txt
Error: failed to show interactive prompt, try using `--yes` to confirm automatically
Caused by:
    0: IO error: not a terminal
    1: not a terminal
Error: Process completed with exit code 1.
```