add bevy lint install instructions (#614)
If you've previously installed bevy_cli and the linter, you need to
manually update it for new installs, especially if Bevy has done a
release and bumped the msrv

This is the error you get for an out of date linter:

```
❯ bevy lint
error: rustc 1.86.0-nightly is not supported by the following packages:
  bevy@0.17.0-rc.1 requires rustc 1.88.0
  bevy_skein@0.3.0-rc.1 requires rustc 1.88.0
  sysinfo@0.37.0 requires rustc 1.88
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.86.0-nightly

Check failed: exit status: 101.
error: command `bevy_lint --profile dev` exited with status code exit status: 101
```

PR modifies readme to show a note

<img width="2270" height="924" alt="screenshot-2025-09-25-at-14 30
44@2x"
src="https://github.com/user-attachments/assets/a1b4966c-c67a-4824-bb9d-3470e73a56c3"
/>