Remove `mdbook-linkcheck` (#684)
`mdbook-linkcheck` breaks currently in our CI:

```
0s
Run mdbook build
 INFO Book building has started
 INFO Running the html backend
 INFO HTML book written to `/home/runner/work/bevy_cli/bevy_cli/docs/book/html`
 INFO Running the linkcheck backend
 INFO Invoking the "linkcheck" renderer
Error: Unable to parse RenderContext

Caused by:
    missing field `sections` at line 1 column 123841
ERROR Renderer exited with non-zero return code.
ERROR Rendering failed
	Caused by: The "linkcheck" renderer failed
Error: Process completed with exit code 101.
Run mdbook build
 INFO Book building has started
 INFO Running the html backend
 INFO HTML book written to `/home/runner/work/bevy_cli/bevy_cli/docs/book/html`
 INFO Running the linkcheck backend
 INFO Invoking the "linkcheck" renderer
Error: Unable to parse RenderContext

Caused by:
    missing field `sections` at line 1 column 123841
ERROR Renderer exited with non-zero return code.
ERROR Rendering failed
	Caused by: The "linkcheck" renderer failed
```

https://github.com/TheBevyFlock/bevy_cli/actions/runs/19582097130/job/56082307183

I think this is due to a new `mdbook` version that is no longer
compatible with `mdbook-linkcheck`.

The Project does not really seem to be maintained anymore, so I would
like to remove it.