Improve error message for failed `cargo metadata` (#378)
# Objective

We always run `cargo metadata` at the start of a CLI command to obtain
more information about workspace and package as well as constructing the
appropriate CLI config.

If this command fails, e.g. because you're not in a cargo workspace, the
output is currently very unhelpful:

```
bevy run web              
Error: Command cargo exited with status code exit status: 101
```

# Solution

- Add more context to the `cargo metadata` error to hint the user what
may have gone wrong
- Log the full command when it errors instead of just the program name

```
bevy-dev run web
Error: failed to obtain package metadata, are you in a cargo workspace?

Caused by:
    Command `cargo metadata --format-version 1` exited with status code exit status: 101
```

# Testing

- Install the CLI from this branch
- Navigate to a non-cargo directory
- Run any `build` or `run` bevy command

---------

Co-authored-by: DAA <42379074+DaAlbrecht@users.noreply.github.com>