Add Linit: missing_trait_for_unit_struct (#574)
# Objective

This new lint checks if a unit structures implements the following
traits:

- Clone
- Copy
- Default

# Note

With how this is set up, if a unit struct does not implement any of
those there will be a lint output for each trait on its own, this also
applies to the fix.

## Example

```rs
use bevy::prelude::*;

pub struct ImplCopy;
```

```toml
[package.metadata.bevy_lint]
missing_default = "warn"
missing_copy = "warn"
missing_clone = "warn"
```


<details><summary>lint output</summary>

```sh
❯ bevy_lint
    Checking test_project v0.1.0 (/tmp/test_project)
warning: defined a unit struct without a `Copy` implementation
 --> src/main.rs:4:1
  |
4 | pub struct ImplCopy;
  | ^^^^^^^^^^^^^^^^^^^^
  |
help: `Copy` can be automatically derived
  |
4 + #[derive(Copy)]
5 | pub struct ImplCopy;
  |

warning: defined a unit struct without a `Clone` implementation
 --> src/main.rs:4:1
  |
4 | pub struct ImplCopy;
  | ^^^^^^^^^^^^^^^^^^^^
  |
help: `Clone` can be automatically derived
  |
4 + #[derive(Clone)]
5 | pub struct ImplCopy;
  |

warning: defined a unit struct without a `Default` implementation
 --> src/main.rs:4:1
  |
4 | pub struct ImplCopy;
  | ^^^^^^^^^^^^^^^^^^^^
  |
help: `Default` can be automatically derived
  |
4 + #[derive(Default)]
5 | pub struct ImplCopy;
  |

warning: `test_project` (bin "test_project") generated 3 warnings (run `cargo fix --bin "test_project"` to apply 3 suggestions)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.30s
```

</details>

`bevy_lint --fix` will result in the following:

```rs
use bevy::prelude::*;

#[derive(Default)]
#[derive(Clone)]
#[derive(Copy)]
pub struct ImplCopy;

fn main() {}
```

and after `cargo fmg`:

```rs
use bevy::prelude::*;

#[derive(Default, Clone, Copy)]
pub struct ImplCopy;

fn main() {}
```


Closes #211, #344

---------

Co-authored-by: BD103 <59022059+BD103@users.noreply.github.com>