Optimistic command execution (#358)
# Objective

We currently check if the required programs and targets are installed
_every time_ when we run the `web` commands.
This adds overhead to the command execution and also makes the logs
noisier.

# Solution

First try to execute the command and only perform the checks and
potential fixes if the command exits with an error.
The `ensure_web_setup` function has been removed entirely.

<details>
<summary>The new version shortens the `--verbose` output</summary>

```diff
DEBUG Using config CliConfig { target: None, features: [], default_features: None }
-DEBUG Running: `rustup --version`
-DEBUG Running: `rustup target list`
-DEBUG Running: `wasm-bindgen --version`
 INFO Compiling to WebAssembly...
DEBUG Running: `cargo build --config profile.web.inherits="dev" --config profile.web-release.inherits="release" --config profile.web-release.strip="debuginfo" --config profile.web-release.opt-level="s" --bin cplx --profile web --target wasm32-unknown-unknown`
    Finished `web` profile [unoptimized + debuginfo] target(s) in 0.23s
 INFO Bundling JavaScript bindings...
DEBUG Running: `wasm-bindgen --no-typescript --out-name cplx --out-dir /home/tim/dev/bevyengine/bevy_complex_repo/app/target/wasm32-unknown-unknown/web --target web /home/tim/dev/bevyengine/bevy_complex_repo/app/target/wasm32-unknown-unknown/web/cplx.wasm`
 INFO No custom `web` folder found, using defaults.
 INFO Open your app at <http://localhost:4000>!
DEBUG Adding response headers {}
```
</details>

There's still things that can be improved (e.g. not logging when we
don't add any response headers), but we already save 3 command
executions!

<details>
<summary>Error example (`wasm32-unknown-unknown` target
missing)</summary>

```diff
DEBUG Using config CliConfig { target: None, features: [], default_features: None }
 INFO Compiling to WebAssembly...
DEBUG Running: `cargo build --config profile.web.inherits="dev" --config profile.web-release.inherits="release" --config profile.web-release.strip="debuginfo" --config profile.web-release.opt-level="s" --bin cplx --profile web --target wasm32-unknown-unknown`
   Compiling proc-macro2 v1.0.93
   Compiling unicode-ident v1.0.15
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.20.2
   Compiling wasm-bindgen-shared v0.2.100
   Compiling bumpalo v3.16.0
   Compiling log v0.4.25
   Compiling rustversion v1.0.19
   Compiling serde v1.0.217
   Compiling wasm-bindgen v0.2.100
   Compiling autocfg v1.4.0
   Compiling pin-project-lite v0.2.16
   Compiling version_check v0.9.5
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.15.2
   Compiling toml_datetime v0.6.8
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

error: could not compile `once_cell` (lib) due to 1 previous error
error: could not compile `pin-project-lite` (lib) due to 1 previous error
+ WARN Failed to run cargo, trying to find automatic fix...
+DEBUG Running: `rustup --version`
+DEBUG Running: `rustup target list`
+Compilation target `wasm32-unknown-unknown` is missing, should I install it for you? [y/n]
```
</details>

To enable these changes, the installation process has been reworked.
Instead of a simple boolean to check prompting, the `AutoInstall` enum
gives us more control about when to automatically install dependencies.
Package installation with versions has been generalized to avoid special
cases for `wasm-bindgen`.
The `CommandExt` has been extended to allow defining required packages
and targets to automatically fix errors and retry the command.

# Testing

- Install the Bevy CLI from this branch:
  ```sh
cargo install --git https://github.com/TheBevyFlock/bevy_cli --branch
optimistic-execution --locked --force bevy_cli
  ```
- Try the happy path on a Bevy repo of your choice:
  ```sh
  bevy run web --verbose
  ```
- Try the error path when a target is missing:
  ```sh
  rustup target remove wasm32-unknown-unknown
  cargo clean  # otherwise the build might just be reused
  bevy run web --verbose
  ```
- Try the error path when a package is missing:
  ```sh
  cargo uninstall wasm-bindgen-cli
  bevy run web --verbose
  ```
- Try the error path when a package has the wrong version:
  ```sh
cargo install wasm-bindgen-cli --version 0.2.92 # or another wrong
version
  bevy run web --verbose
  ```

# Follow-up work

- Add a `--no` flag analogous to the `--yes` flag, which will use
`AutoInstall::Never`
- Further clean up verbose logging
- Align the style of the logging to blend in more nicely with `cargo`